### ISSUE TITLE
Exception in AiSession.BeforeStart: WcApi.Load() should not be called multiple times!

### ISSUE THREAD

**Issue by Maeyanie** [jturp/AiEnabled#1]
I recently noticed AiEnabled seems to have stopped working on my server at some point. Checking the logs, I found this in AiEnabled.log:
```
[20:18:42.729] [T23] [DS=True] DEBUG | Log Started (v1.4.5)
[20:18:42.731] [T23] [DS=True] DEBUG | Defense Shields Mod found. API loaded successfully = True
[20:18:42.738] [T23] [DS=True] DEBUG | WeaponCore Mod found. API loaded successfully = True
[20:18:42.741] [T23] [DS=True] ERROR | Exception in AiSession.BeforeStart: WcApi.Load() should not be called multiple times!
   at AiEnabled.API.WcApi.Load(Action readyCallback, Boolean getWeaponDefinitions)
   at AiEnabled.AiSession.BeforeStart()
[20:18:42.758] [T23] [DS=True] DEBUG | Unloading mod data. Registered = False
[20:18:42.773] [T23] [DS=True] DEBUG | Mod unloaded successfully
```

I haven't tried it in a clean save yet, so it could be a mod interaction, though looking at your code it would be weird if it was... then again, it's weird it's happening at all.

**Comment by Maeyanie** [comment]
Replacing the line which throws the exception with a "return" _seems_ to still work... I haven't noticed any problems in testing at least.

**Comment by jturp** [comment]
I think the bigger issue is that it's somehow being called *twice* during load, which is what is causing the error. I'm not sure how that's possible, but I will see about maybe checking if it's already loaded first before calling it again.

I will also reach out to DarkStar to see how it even *can* be called twice given that is only done during the initial load phase for the game.

**Comment by Maeyanie** [comment]
Yeah, I tried debugging that one and had no luck at all, but then I also don't know the codebase. It did seem pretty weird.
